Psc 111 impl proposal expiry time
axieinfinity/ronin-dpos-contracts pull request #108
Opened 2022-12-02 09:05 UTC by nxqbao

### Description
- https://skymavis.atlassian.net/jira/software/projects/PSC/boards/47?selectedIssue=PSC-111

### Checklist
- [x] I have clearly commented on all the main functions following the [NatSpec Format](https://docs.soliditylang.org/en/v0.8.0/natspec-format.html)
- [x] The box that allows repo maintainers to update this PR is checked
- [ ] I tested locally to make sure this feature/fix works

2022-12-05 03:31 UTC, ducthotran2010 requested changes
With this pattern, we cannot relay the expired votes on the mainchain.

2022-12-05 03:31 UTC, ducthotran2010 commented on contracts/extensions/GovernanceAdmin.sol
> +  function setProposalExpiryDuration(uint256 _expiryDuration) external onlyAdmin {
```suggestion
  function setProposalExpiryDuration(uint256 _expiryDuration) external onlySelfCall {
```

2022-12-05 03:31 UTC, ducthotran2010 commented on contracts/extensions/GovernanceAdmin.sol
> +   * - Only admin can call this method.
Update this

2022-12-05 03:31 UTC, ducthotran2010 commented on contracts/extensions/sequential-governance/CoreGovernance.sol
> +      emit ProposalExpired(_vote.hash);
This should be checked before casting the new votes?

2022-12-05 03:37 UTC, nxqbao commented on contracts/extensions/GovernanceAdmin.sol
> +   * - Only admin can call this method.
```suggestion
   * - Only allowing self-call to this method, since this contract does not have admin.
```

2022-12-07 06:37 UTC, ducthotran2010 reviewed
Need some small changes before merging

2022-12-07 06:37 UTC, ducthotran2010 commented on contracts/libraries/Proposal.sol
> +    require(_proposal.expiryTimestamp <= block.timestamp + _maxExpiryDuration, "Proposal: invalid expiry timestamp");
I guess we don't want this check on mainchain

2022-12-07 06:37 UTC, ducthotran2010 commented on contracts/extensions/sequential-governance/CoreGovernance.sol
> +      if (_latestProposalVote.status == VoteStatus.Expired) {
```solidity
      ProposalVote storage _latestProposalVote = vote[_chainId][_round];
      _syncExpiryVote(); // This function is to sync `status` whether the current vote is expired
      if (_latestProposalVote.status == VoteStatus.Expired) {
```

2022-12-07 06:37 UTC, ducthotran2010 commented on contracts/extensions/sequential-governance/CoreGovernance.sol
> +    vote[_chainId][_round].hash = _proposalHash;
I think using too much "if-else" clause can cause misleading

2022-12-07 06:37 UTC, ducthotran2010 commented on contracts/extensions/sequential-governance/CoreGovernance.sol
> +    } else if (_forVoteWeight >= _minimumForVoteWeight) {
We can move this check before recovering signature for gas saving

2022-12-07 06:37 UTC, ducthotran2010 commented on contracts/extensions/sequential-governance/CoreGovernance.sol
> +    return _vote.sig[_voter].v != 0;
```suggestion
    Signature storage _sig = _vote.sig[_voter];
    return uint256(_sig.v) > 0 || uint256(_sig.r) > 0 || uint256(_sig.s) > 0;
```

2022-12-07 06:37 UTC, ducthotran2010 commented on contracts/ronin/RoninGovernanceAdmin.sol
> +  constructor(
Should add a function to remove the expiry vote

2022-12-07 06:46 UTC, ducthotran2010 commented on contracts/mainchain/MainchainGovernanceAdmin.sol
> +  ) GovernanceAdmin(_roninTrustedOrganizationContract, _bridgeContract, _proposalExpiryDuration) {
```suggestion
    address[] memory _relayers
  ) GovernanceAdmin(_roninTrustedOrganizationContract, _bridgeContract, 0) {
```

2022-12-07 09:14 UTC, ducthotran2010 approved these changes
Some naming conflicts found:
- Expired voting: `_tryDeleteExpiredVotingRound`
- Expiry duration: `_proposalExpiryDuration`

2022-12-07 09:14 UTC, ducthotran2010 commented on contracts/extensions/sequential-governance/CoreGovernance.sol
> +  function _tryDeleteExpiredVotingRound(ProposalVote storage _proposalVote) private returns (bool _isExpired) {
Please consider exposing this function (in `RoninGovernanceAdmin`) to support clearing expired votes without create new proposals

2022-12-07 09:14 UTC, ducthotran2010 commented on contracts/extensions/sequential-governance/CoreGovernance.sol
> +    if (_getChainType() == ChainType.RoninChain && _proposalVote.expiryTimestamp <= block.timestamp) {
```suggestion
    _isExpired = _getChainType() == ChainType.RoninChain && _proposalVote.expiryTimestamp <= block.timestamp;
    if (_isExpired) {
```

2022-12-07 09:14 UTC, ducthotran2010 commented on contracts/extensions/sequential-governance/CoreGovernance.sol
> +      return true;
```suggestion
```

2022-12-07 10:21 UTC, merged