Implement function emergency exit for Validators
axieinfinity/ronin-dpos-contracts pull request #126
Opened 2022-12-15 10:56 UTC by ducthotran2010

### Description
Mainly implement function emergency exit for Validators:
1. Events changed: `BlockProducerSetUpdated` & `BridgeOperatorSetUpdated` add `epoch` field → Bridge operator set voting in `RoninGovernanceAdmin` is changed.
2. Callback to `RoninGovernanceAdmin` contract to create new voting for an emergency exit request → Add new ballot & voting round
3. Add cronjob at epoch ending: recycle the expired locked funds.

### ABI Changes

**Ronin Validator Set**
- Event changed: _**BlockProducerSetUpdated**_ + _**BridgeOperatorSetUpdated**_
- New ABI: See `IEmergencyExit.sol` + `ICommonInfo.sol`

**GovernanceAdmin**
- Function changed: `getBridgeOperatorVotingSignatures` + `bridgeOperatorsVoted` + `voteBridgeOperatorsBySignatures`
- New ABI: `createEmergencyExitVote` + `voteEmergencyExit`

### Checklist
- [x] I have clearly commented on all the main functions following the [NatSpec Format](https://docs.soliditylang.org/en/v0.8.0/natspec-format.html)
- [x] The box that allows repo maintainers to update this PR is checked
- [x] I tested locally to make sure this feature/fix works

2022-12-22 06:29 UTC, ducthotran2010 commented
The commit [25e20f3](https://github.com/axieinfinity/ronin-dpos-contracts/pull/126/commits/25e20f31dafbb696925a8f6ccbb69c8f8e907e13) cause:
```
Warning: Contract code size is 25512 bytes and exceeds 24576 bytes (a limit introduced in Spurious Dragon). This contract may not be deployable on Mainnet. Consider enabling the optimizer (with a low "runs" value!), turning off revert strings, or using libraries.
  --> contracts/ronin/validator/RoninValidatorSet.sol:10:1:
   |
10 | contract RoninValidatorSet is Initializable, CoinbaseExecution, SlashingExecution {
   | ^ (Relevant source part starts here and spans across multiple lines).
```

2022-12-22 08:07 UTC, nxqbao requested changes

2022-12-22 08:07 UTC, nxqbao commented on contracts/extensions/isolated-governance/IsolatedGovernance.sol
> +      _proposal.status = VoteStatus.Expired;
Unreachable code

2022-12-22 08:14 UTC, ducthotran2010 commented on contracts/interfaces/IRoninGovernanceAdmin.sol
> +  function createEmergencyExitVote(
```suggestion
  function createEmergencyExitPoll(
```

2022-12-22 08:15 UTC, ducthotran2010 commented on contracts/ronin/RoninGovernanceAdmin.sol
> +  mapping(bytes32 => IsolatedVote) internal _emergecyVote;
```suggestion
  mapping(bytes32 => IsolatedVote) internal _emergencyPoll;
```

2022-12-22 08:17 UTC, ducthotran2010 commented on contracts/ronin/validator/EmergencyExit.sol
> +  function unlockFundForEmergencyExitRequest(address _consensusAddr, address payable _recipient) external onlyAdmin {
```suggestion
  function execReleaseLockedFundForEmergencyExitRequest(address _consensusAddr, address payable _recipient) external onlyAdmin {
```

2022-12-22 08:18 UTC, ducthotran2010 commented on contracts/ronin/validator/EmergencyExit.sol
> +        continue;
```solidity
if (_length > 1) {
  _lockedConsensusList[_i] = _lockedConsensusList[--_length];
}

2022-12-22 08:19 UTC, ducthotran2010 commented on contracts/ronin/validator/EmergencyExit.sol
> +    }
IMO we should not revert the call from governance admin poll

2022-12-22 08:20 UTC, ducthotran2010 commented on contracts/ronin/validator/EmergencyExit.sol
> +    }
```solidity
bool _notFound = _exitInfo[_consensusAddr].recycleAt == 0;
```

2022-12-22 09:07 UTC, nxqbao commented on contracts/ronin/validator/EmergencyExit.sol
> +    }
I think G.A. should handle the revert by itself. Reverting here does not affect the caller.

2022-12-22 10:30 UTC, ducthotran2010 commented
The commit [c50ea54](https://github.com/axieinfinity/ronin-dpos-contracts/pull/126/commits/c50ea54478a8ead323e2f9783e1bed13421556e1) cause:
```
Warning: Contract code size is 25954 bytes and exceeds 24576 bytes (a limit introduced in Spurious Dragon). This contract may not be deployable on Mainnet. Consider enabling the optimizer (with a low "runs" value!), turning off revert strings, or using libraries.
  --> contracts/ronin/validator/RoninValidatorSet.sol:10:1:
   |
10 | contract RoninValidatorSet is Initializable, CoinbaseExecution, SlashingExecution {
   | ^ (Relevant source part starts here and spans across multiple lines).
```

2022-12-22 10:41 UTC, ducthotran2010 commented on contracts/ronin/validator/RoninValidatorSet.sol
> +    uint256[2] calldata __emergencyExitConfigs
These variables work fine, I prefer to not change them

2022-12-22 10:43 UTC, ducthotran2010 commented on contracts/ronin/RoninGovernanceAdmin.sol
> +  function voteEmergencyExit(
Updated the function to change polling status

2022-12-23 07:40 UTC, nxqbao approved these changes

2022-12-23 07:46 UTC, merged

2023-05-22 09:08 UTC, nxqbao commented on contracts/ronin/validator/storage-fragments/JailingStorage.sol
> +  mapping(address => uint256) internal _emergencyExitJailedTimestamp;
I think there are some mis-naming here.