[Staking] Send last reward for revoked candidates
axieinfinity/ronin-dpos-contracts pull request #164
Opened 2023-02-13 10:09 UTC by nxqbao

### Description

### Checklist
- [x] I have clearly commented on all the main functions following the [NatSpec Format](https://docs.soliditylang.org/en/v0.8.0/natspec-format.html)
- [x] The box that allows repo maintainers to update this PR is checked
- [x] I tested locally to make sure this feature/fix works

2023-02-13 10:10 UTC, nxqbao commented
Instead of settling last reward by new function, we can do it in the `deprecatePools` instead.

2023-02-14 05:08 UTC, ducthotran2010 requested changes

2023-02-14 05:35 UTC, nxqbao commented on test/validator/RoninValidatorSet-CoinbaseExecution.test.ts
> +    });
added

2023-02-14 05:35 UTC, nxqbao commented on contracts/ronin/staking/RewardCalculation.sol
> +    uint256 _period
updated with docs

2023-02-14 06:21 UTC, ducthotran2010 approved these changes

2023-02-15 05:53 UTC, merged