[TrustedOrg] Lack of Check When Updating Trusted Organization
axieinfinity/ronin-dpos-contracts pull request #174
Opened 2023-02-20 09:12 UTC by nxqbao

### Description
- Adds a check when updating a trusted organization to ensure that the consensus, governor, and bridge voter addresses are all distinct from each other in `updateTrustedOrganizations` method.

### Contract changes

The table below shows the following info:
- **Logic**: the logic is changed.
- **ABI**: the ABI is changed.
- **Init data**: new storage field is declared and needs initializing.
- **Dependent**: needs to be changed due to changes in other contracts.

| **Contract name** | **Logic** | **ABI** | **Init data** | **Dependent** |
|-------------------|:---------:|:-------:|:-------------:|:-------------:|
| BridgeTracking    |           |         |               |               |
| GovernanceAdmin   |           |         |               |               |
| Maintenance       |           |         |               |               |
| SlashIndicator    |           |         |               |               |
| Staking           |           |         |               |               |
| StakingVesting    |           |         |               |               |
| RoninTrustedOrganization      |     [x]      |         |               |               |
| ValidatorSet      |           |         |               |               |

### Checklist
- [ ] I have clearly commented on all the main functions following the [NatSpec Format](https://docs.soliditylang.org/en/v0.8.0/natspec-format.html)
- [ ] The box that allows repo maintainers to update this PR is checked
- [ ] I tested locally to make sure this feature/fix works

2023-02-20 10:39 UTC, ducthotran2010 requested changes
- Fix the naming issue
- Add comment for the new function

2023-02-20 10:39 UTC, ducthotran2010 commented on contracts/multi-chains/RoninTrustedOrganization.sol
> +  function _sanityCheckTOData(TrustedOrganization memory _v) private pure {
```suggestion
  
 /**
  * @dev Hook that checks trusted organization's data. Reverts if the requirements are not met.
  *
  * Requirements:
  * - The weight must be larger than 0.
  * - The consensus address, governor address, and bridge voter address are different.
  *
  */
  function _sanityCheckTrustedOrganizationData(TrustedOrganization memory _v) private pure {
```

2023-02-20 10:39 UTC, ducthotran2010 commented on contracts/multi-chains/RoninTrustedOrganization.sol
> +    _sanityCheckTOData(_v);
```suggestion
    _sanityCheckTrustedOrganizationData(_v);
```

2023-02-20 10:39 UTC, ducthotran2010 commented on contracts/multi-chains/RoninTrustedOrganization.sol
> +    _sanityCheckTOData(_v);
```suggestion
    _sanityCheckTrustedOrganizationData(_v);
```

2023-02-21 03:20 UTC, ducthotran2010 approved these changes

2023-02-23 10:03 UTC, h4x0r31337 approved these changes

2023-02-27 03:56 UTC, h4x0r31337 approved these changes

2023-02-27 03:57 UTC, h4x0r31337 approved these changes

2023-03-03 03:02 UTC, merged