[*] Reduce code size: efficient hashing to avoid memory expansion
axieinfinity/ronin-dpos-contracts pull request #241
Opened 2023-06-05 16:36 UTC by TuDo1403

### Description
This PR reduce code size by using assembly to perform hashing to avoid new memory allocation which is cheaper in gas cost and lower code size.
### Contract changes

The table below shows the following info:
- **Logic**: the logic is changed.
- **ABI**: the ABI is changed.
- **Init data**: new storage field is declared and needs initializing.
- **Dependent**: needs to be changed due to changes in other contracts.

| **Contract name** | **Logic** | **ABI** | **Init data** | **Dependent** |
|-------------------|:---------:|:-------:|:-------------:|:-------------:|
| BridgeTracking    |           |         |               |               |
| GovernanceAdmin   |           |         |               |               |
| Maintenance       |           |         |               |               |
| SlashIndicator    |           |         |               |               |
| Staking           |           |         |               |               |
| StakingVesting    |           |         |               |               |
| ValidatorSet      |           |         |               |               |

### Checklist
- [x] I have clearly commented on all the main functions following the [NatSpec Format](https://docs.soliditylang.org/en/v0.8.0/natspec-format.html)
- [x] The box that allows repo maintainers to update this PR is checked
- [x] I tested locally to make sure this feature/fix works

2023-06-06 06:55 UTC, nxqbao commented on contracts/libraries/BridgeOperatorsBallot.sol
> +  function hash(BridgeOperatorSet memory _ballot) internal pure returns (bytes32 digest) {
Please change the first param in the struct methods of all libraries (which contains only one struct) to `self` to adapt to the new code convention. 

```suggestion
  function hash(BridgeOperatorSet memory self) internal pure returns (bytes32 digest) {
```

2023-06-07 07:57 UTC, TuDo1403 commented on contracts/libraries/BridgeOperatorsBallot.sol
> +  function hash(BridgeOperatorSet memory _ballot) internal pure returns (bytes32 digest) {
updated.

2023-06-08 04:50 UTC, ducthotran2010 requested changes

2023-06-08 04:50 UTC, ducthotran2010 commented on yarn.lock
I found no package addition in `package.json` file. Is this file change on purpose?

2023-06-08 04:50 UTC, ducthotran2010 commented on logs/storage.txt
I don't think updating the hash mechanism lead to change storage.

2023-06-08 04:50 UTC, ducthotran2010 commented on logs/storage_layout.txt
Same

2023-06-08 06:21 UTC, TuDo1403 commented on logs/storage.txt
deleted.

2023-06-08 06:21 UTC, TuDo1403 commented on logs/storage_layout.txt
deleted.

2023-06-08 06:44 UTC, TuDo1403 commented on yarn.lock
change becauses of changes in branch reduce-contract-size

2023-06-08 07:11 UTC, ducthotran2010 approved these changes
Logic looks good

2023-06-08 07:23 UTC, merged