[*] Reduce contract size
axieinfinity/ronin-dpos-contracts pull request #243
Opened 2023-06-06 03:53 UTC by TuDo1403

### Description
This PR reduces overall contract sizes using following techniques:
- Convert require string to revert custom error
- Uncheck for loop iteration
- Move reused modifier logic to internal function
### Contract changes

The table below shows the following info:
- **Logic**: the logic is changed.
- **ABI**: the ABI is changed.
- **Init data**: new storage field is declared and needs initializing.
- **Dependent**: needs to be changed due to changes in other contracts.

| **Contract name** | **Logic** | **ABI** | **Init data** | **Dependent** |
|-------------------|:---------:|:-------:|:-------------:|:-------------:|
| BridgeTracking    |           |         |               |               |
| GovernanceAdmin   |           |         |               |               |
| Maintenance       |           |         |               |               |
| SlashIndicator    |           |         |               |               |
| Staking           |           |         |               |               |
| StakingVesting    |           |         |               |               |
| ValidatorSet      |           |         |               |               |

### Checklist
- [x] I have clearly commented on all the main functions following the [NatSpec Format](https://docs.soliditylang.org/en/v0.8.0/natspec-format.html)
- [x] The box that allows repo maintainers to update this PR is checked
- [x] I tested locally to make sure this feature/fix works

2023-06-07 06:08 UTC, ducthotran2010 requested changes
Most of the issues come from:
- Confused `import` grouping
- Funciton naming
- Invalid trailing line
- Invalid keyword orders (`error` -> `using`)

Some suggestions that should be applied:
- Inline uncheck for-loop

2023-06-07 06:08 UTC, ducthotran2010 commented on contracts/extensions/GovernanceAdmin.sol
> +import "../libraries/ErrorHandler.sol";
```suggestion
```

2023-06-07 06:08 UTC, ducthotran2010 commented on contracts/extensions/GovernanceAdmin.sol
> +
```suggestion
```

2023-06-07 06:08 UTC, ducthotran2010 commented on contracts/extensions/GovernanceAdmin.sol
> +    _onlySelfCall();
```suggestion
    _requireSelfCall();
```

2023-06-07 06:08 UTC, ducthotran2010 commented on contracts/extensions/GovernanceAdmin.sol
> +  function _onlySelfCall() internal view virtual {
```suggestion
  function _requireSelfCall() internal view virtual {
```

2023-06-07 06:08 UTC, ducthotran2010 commented on contracts/extensions/bridge-operator-governance/BOsGovernanceProposal.sol
> +
Place error defines after `using` keywords

2023-06-07 06:08 UTC, ducthotran2010 commented on contracts/extensions/bridge-operator-governance/BOsGovernanceRelay.sol
> +
```suggestion
```

2023-06-07 06:08 UTC, ducthotran2010 commented on contracts/extensions/collections/HasProxyAdmin.sol
> +    _onlyAdmin();
```suggestion
    _requireAdmin();
```

2023-06-07 06:08 UTC, ducthotran2010 commented on contracts/extensions/collections/HasProxyAdmin.sol
> +  function _onlyAdmin() internal view {
```suggestion
  function _requireAdmin() internal view {
```

2023-06-07 06:08 UTC, ducthotran2010 commented on contracts/extensions/collections/HasProxyAdmin.sol
> +import "../../libraries/Errors.sol";
Weird grouping

2023-06-07 06:08 UTC, ducthotran2010 commented on contracts/extensions/forwarder/Forwarder.sol
> +import { ErrorHandler } from "../../libraries/ErrorHandler.sol";
Weird import grouping

2023-06-07 06:08 UTC, ducthotran2010 commented on contracts/extensions/forwarder/Forwarder.sol
> +  using ErrorHandler for bool;
```suggestion
  using ErrorHandler for bool;

  /**
   * @dev Error thrown when an invalid forward value is provided.
   */
  error ErrInvalidForwardValue();
```

2023-06-07 06:08 UTC, ducthotran2010 commented on contracts/extensions/forwarder/Forwarder.sol
> +      }
Should we make it as an inline uncheck

2023-06-07 06:08 UTC, ducthotran2010 commented on contracts/libraries/Errors.sol
CommonErrors.sol

2023-06-07 06:08 UTC, ducthotran2010 commented on contracts/libraries/GlobalProposal.sol
> +        ++_i;
Nani?
```suggestion
      unchecked {
        ++_i;
```

2023-06-07 06:08 UTC, ducthotran2010 commented on contracts/libraries/AddressArrayUtils.sol
> +error ErrDuplicated(bytes4 msgSig);
Should we move this error into the lib?

2023-06-07 06:08 UTC, ducthotran2010 commented on contracts/libraries/BridgeOperatorsBallot.sol
> +import "../libraries/Errors.sol";
Weird grouping

2023-06-07 06:08 UTC, ducthotran2010 commented on contracts/libraries/Proposal.sol
> +import "../libraries/Errors.sol";
Could it be:
```solidity
import { UsedErrors,... } from "../libraries/Errors.sol";
```

2023-06-07 06:08 UTC, ducthotran2010 commented on contracts/libraries/Roles.sol
> +  ADMIN, // 0
1. Reserve a slot for unknown role
2. Only use prefix `s` for arrays
```suggestion
enum Role {
  UNKNOWN,
  ADMIN,
```

2023-06-07 06:08 UTC, ducthotran2010 commented on contracts/mainchain/MainchainGovernanceAdmin.sol
> +import "../libraries/ErrorHandler.sol";
Weird grouping

2023-06-07 06:08 UTC, ducthotran2010 commented on contracts/ronin/gateway/BridgeTracking.sol
>    }
Does it return for the whole trxn?

2023-06-07 06:08 UTC, ducthotran2010 commented on contracts/ronin/staking/BaseStaking.sol
> +  function _onlyEmptyValue() private view {
```suggestion
  function _requireValue() private view {
```

2023-06-07 06:08 UTC, ducthotran2010 commented on contracts/ronin/validator/CoinbaseExecution.sol
> +  function _onlyCoinbase() private view {
```suggestion
  function _requireCoinbase() private view {
```

2023-06-07 06:08 UTC, ducthotran2010 commented on logs/contract-code-sizes-1685028054516.log
Do we need this file?

2023-06-07 06:44 UTC, TuDo1403 commented on contracts/extensions/GovernanceAdmin.sol
> +import "../libraries/ErrorHandler.sol";
removed.

2023-06-07 06:45 UTC, TuDo1403 commented on contracts/extensions/GovernanceAdmin.sol
> +    _onlySelfCall();
fixed.

2023-06-07 06:46 UTC, TuDo1403 commented on contracts/extensions/bridge-operator-governance/BOsGovernanceProposal.sol
> +
fixed.

2023-06-07 06:52 UTC, TuDo1403 commented on contracts/ronin/validator/CoinbaseExecution.sol
> +  function _onlyCoinbase() private view {
resolved.

2023-06-07 06:53 UTC, TuDo1403 commented on contracts/extensions/GovernanceAdmin.sol
> +  function _onlySelfCall() internal view virtual {
resolved.

2023-06-07 07:01 UTC, TuDo1403 commented on contracts/ronin/gateway/BridgeTracking.sol
>    }
fixed.

2023-06-07 07:02 UTC, TuDo1403 commented on contracts/ronin/staking/BaseStaking.sol
> +  function _onlyEmptyValue() private view {
resolved.

2023-06-07 07:07 UTC, TuDo1403 commented on contracts/extensions/collections/HasProxyAdmin.sol
> +import "../../libraries/Errors.sol";
resolved.

2023-06-07 07:07 UTC, TuDo1403 commented on contracts/extensions/forwarder/Forwarder.sol
> +import { ErrorHandler } from "../../libraries/ErrorHandler.sol";
resolved.

2023-06-07 07:21 UTC, TuDo1403 commented on contracts/libraries/Errors.sol
updated.

2023-06-07 07:21 UTC, TuDo1403 commented on contracts/libraries/GlobalProposal.sol
> +        ++_i;
resolved.

2023-06-07 07:22 UTC, TuDo1403 commented on contracts/libraries/Proposal.sol
> +import "../libraries/Errors.sol";
updated.

2023-06-07 07:22 UTC, TuDo1403 commented on contracts/libraries/Roles.sol
> +  ADMIN, // 0
renamed.

2023-06-07 07:22 UTC, TuDo1403 commented on contracts/mainchain/MainchainGovernanceAdmin.sol
> +import "../libraries/ErrorHandler.sol";
fixed.

2023-06-07 07:25 UTC, TuDo1403 commented on logs/contract-code-sizes-1685028054516.log
deleted.

2023-06-07 07:27 UTC, TuDo1403 commented on contracts/libraries/AddressArrayUtils.sol
> +error ErrDuplicated(bytes4 msgSig);
only RoninTrustedOrganization.sol and CandidateStaking.sol which import AddressArrayUtils lib used this error.

2023-06-07 07:27 UTC, TuDo1403 commented on contracts/libraries/BridgeOperatorsBallot.sol
> +import "../libraries/Errors.sol";
resolved.

2023-06-07 07:33 UTC, TuDo1403 commented on contracts/extensions/forwarder/Forwarder.sol
> +      }
unchecked block cannot be inlined.

2023-06-08 04:38 UTC, ducthotran2010 commented
This PR has some issues related to prettier

2023-06-09 03:53 UTC, nxqbao commented
PR looks good, saved a huge size.

2023-06-09 05:29 UTC, nxqbao commented on contracts/libraries/DeprecatedSlots.sol
> + * @notice The reason for these contracts is for preserving the slots for already deployed contracts.
```suggestion
 * The purpose of these contracts is to preserve the slots for already deployed contracts.
```

2023-06-09 05:29 UTC, nxqbao commented on contracts/libraries/DeprecatedSlots.sol
> + * @title Deprecated Contracts
Should move this file to `contracts/utils/DeprecatedSlots.sol`, since these contracts are not library.

2023-06-09 05:29 UTC, nxqbao commented on contracts/libraries/DeprecatedSlots.sol
> +  address private ____deprecatedSI;
Please add `@custom:deprecated` NatSpecs comment for this and other relevant variables.

2023-06-09 05:29 UTC, nxqbao commented on contracts/libraries/GlobalProposal.sol
> +      } else revert ErrUnsupportedTarget();
Should add proposal hash and target number for ease when debugging, since this error is in a loop.

2023-06-09 05:29 UTC, nxqbao commented on contracts/libraries/Proposal.sol
> +      if (gasleft() <= _proposal.gasAmounts[_i]) revert ErrInsufficientGas();
This error is in a loop, please add proposal hash into the error.

2023-06-09 05:29 UTC, nxqbao commented on contracts/libraries/Role.sol
> + */
```suggestion
/**
 * @notice Sort role by contract or EOA in parity order.
 * @dev The 1st (the right bit) most is reserved. EOA addresses are even (`*0`), contract addresses are odd (`*1`)
 */
```

2023-06-09 05:29 UTC, nxqbao commented on contracts/libraries/Role.sol
> +  RONIN_TRUSTED_ORGANIZATION_CONTRACT // 21
```suggestion
   /*  0 */ UNKNOWN_0,
   /*  1 */ UNKNOWN_1,
   /*  2 */ ADMIN,
   /*  3 */ PAUSE_ENFORCER_CONTRACT,
   /*  4 */ COINBASE,
   /*  5 */ BRIDGE_CONTRACT,
   /*  6 */ GOVERNOR,
   /*  7 */ BRIDGE_TRACKING_CONTRACT,
   /*  8 */ CANDIDATE_ADMIN,
   /*  9 */ GOVERNANCE_ADMIN_CONTRACT,
   /* 10 */ WITHDRAWAL_MIGRATOR,
   /* 11 */ MAINTENANCE_CONTRACT,
   /* 12 */ BRIDGE_OPERATOR,
   /* 13 */ SLASH_INDICATOR_CONTRACT,
   /* 14 */ BLOCK_PRODUCER,
   /* 15 */ STAKING_VESTING_CONTRACT,
   /* 16 */ VALIDATOR_CANDIDATE,
   /* 17 */ VALIDATOR_CONTRACT,
   /* 18 */ RESERVED_0,
   /* 19 */ STAKING_CONTRACT,
   /* 20 */ RESERVED_1,
   /* 21 */ RONIN_TRUSTED_ORGANIZATION_CONTRACT
```

2023-06-09 05:29 UTC, nxqbao commented on contracts/libraries/Token.sol
> +  error ErrUnsupportedStandard();
```suggestion
  /// @dev Error indicating that the provided information is invalid.
  error ErrInvalidInfo();

  /// @dev Error indicating that the minting of ERC20 tokens has failed.
  error ErrERC20MintingFailed();

  /// @dev Error indicating that the minting of ERC721 tokens has failed.
  error ErrERC721MintingFailed();

  /// @dev Error indicating that an unsupported standard is encountered.
  error ErrUnsupportedStandard();
```

2023-06-09 05:29 UTC, nxqbao commented on contracts/ronin/gateway/RoninGatewayV2.sol
> +  address private ____deprecated1;
```suggestion
  /// @custom:deprecated Previously `_validatorContract` (non-zero value)
  address private ____deprecated0;
  /// @custom:deprecated Previously `_bridgeTrackingContract` (non-zero value)
  address private ____deprecated1;
```

2023-06-09 05:29 UTC, nxqbao commented on contracts/ronin/gateway/RoninGatewayV2.sol
> +  /// @custom:deprecated previously `_trustedOrgContract` (non-zero value)
```suggestion
  /// @custom:deprecated Previously `_trustedOrgContract` (non-zero value)
```

2023-06-09 05:29 UTC, nxqbao commented on contracts/ronin/slash-indicator/CreditScore.sol
> +    if (_cutOffPercentage > _MAX_PERCENTAGE) revert ErrInvalidCutOffPercentageConfig();
```suggestion
    if (_gainScore > _maxScore) revert ErrInvalidCreditScoreConfig();
    if (_cutOffPercentage > _MAX_PERCENTAGE) revert ErrInvalidCutOffPercentageConfig();
```

2023-06-09 05:29 UTC, nxqbao commented on contracts/ronin/staking/CandidateStaking.sol
>        revert ErrUnstakeTooEarly();
```suggestion
    if (_pool.lastDelegatingTimestamp[_requester] + _cooldownSecsToUndelegate > block.timestamp) {
      revert ErrUnstakeTooEarly();
    }
```

2023-06-09 05:29 UTC, nxqbao commented on contracts/ronin/Maintenance.sol
> +    if (!_validator.epochEndingAt(_endedAtBlock)) revert ErrEndBlockOutOfRange();
Remove blank space among these `if`.
Add `{}` for in-new-line `revert`.

2023-06-09 05:29 UTC, nxqbao commented on contracts/ronin/Maintenance.sol
> +    if (checkMaintained(_consensusAddr, block.number)) revert ErrAlreadyOnMaintenance();
Remove blank space among these if. Add {} for in-new-line revert.

2023-06-09 05:29 UTC, nxqbao commented on contracts/ronin/Maintenance.sol
> +    if (_minOffsetToStartSchedule >= _maxOffsetToStartSchedule) revert ErrInvalidOffsetToStartScheduleConfigs();
```suggestion
    if (_minMaintenanceDurationInBlock >= _maxMaintenanceDurationInBlock) revert ErrInvalidMaintenanceDurationConfig();
    if (_minOffsetToStartSchedule >= _maxOffsetToStartSchedule) revert ErrInvalidOffsetToStartScheduleConfigs();
```

2023-06-09 05:48 UTC, ducthotran2010 commented on contracts/extensions/GovernanceAdmin.sol
> +     */
Unexpected NatSpec tag "dev" with value in inline assembly.solidity

2023-06-09 05:56 UTC, ducthotran2010 commented on contracts/libraries/EmergencyExitBallot.sol
> +     **/
Unexpected NatSpec tag "dev" with value in inline assembly.solidity(6269)

2023-06-09 06:19 UTC, ducthotran2010 requested changes

2023-06-09 06:19 UTC, ducthotran2010 commented on contracts/libraries/Role.sol
> +}
I don't think we should merge these 2 sets together including EOA roles, and contract types.

2023-06-09 09:32 UTC, ducthotran2010 commented
This PR includes heavy changes, and needs some extra attention from the security aspect.

2023-06-09 09:34 UTC, ducthotran2010 approved these changes

2023-06-09 10:20 UTC, nxqbao commented on test/helpers/utils.ts
> +const ROLES = [
Rename to `CONTRACT_TYPES`.

2023-06-09 10:20 UTC, nxqbao commented on contracts/extensions/collections/HasContracts.sol
> +      revert ErrUnexpectedInternalCall(msg.sig, contractType, expectedCaller, msg.sender);
```suggestion
    if (msg.sender != expectedCaller) {
      revert ErrUnexpectedInternalCall(msg.sig, contractType, expectedCaller, msg.sender);
    }
```

2023-06-09 10:20 UTC, nxqbao commented on hardhat.config.ts
> +    outputFile: './logs/contract-code-sizes.log',
```suggestion
    outputFile: './logs/contract_code_sizes.log',
```

2023-06-12 07:33 UTC, nxqbao commented on contracts/libraries/Token.sol
> +    assembly {
```suggestion
  function hash(Info memory _info) internal pure returns (bytes32 digest) {
    // keccak256(abi.encode(INFO_TYPE_HASH, _info.erc, _info.id, _info.quantity))
    assembly {
```

2023-06-12 07:33 UTC, nxqbao commented on contracts/libraries/Token.sol
> +    ) revert ErrInvalidInfo();
Wrong `!`, please double check this

```suggestion
    if (
      !((_info.erc == Standard.ERC20 && _info.quantity > 0 && _info.id == 0) ||
      (_info.erc == Standard.ERC721 && _info.quantity == 0))
    ) revert ErrInvalidInfo();
```

2023-06-12 07:33 UTC, nxqbao commented on contracts/libraries/Token.sol
>      if (!_success) {
Please change the below `string(abi.encodePacked)` into custom error.

https://github.com/axieinfinity/ronin-dpos-contracts/pull/243/files#diff-44e5707d9a5ca48b8e94d327904aa677cce540d6c8d7f465a69e185b7d7db3d2R81-R94

2023-06-12 07:33 UTC, nxqbao commented on contracts/libraries/Token.sol
> +    assembly {
```suggestion
  function hash(Owner memory _owner) internal pure returns (bytes32 digest) {
    // keccak256(abi.encode(OWNER_TYPE_HASH, _owner.addr, _owner.tokenAddr, _owner.chainId))
    assembly {
```

2023-06-12 07:33 UTC, nxqbao commented on contracts/mainchain/MainchainGatewayV2.sol
> +      revert ErrInvalidChainId(msg.sig, _receipt.mainchain.chainId, block.chainid);
```suggestion
    if (_receipt.mainchain.chainId != block.chainid) {
      revert ErrInvalidChainId(msg.sig, _receipt.mainchain.chainId, block.chainid);
    }
```

2023-06-12 07:33 UTC, nxqbao commented on contracts/mainchain/MainchainGatewayV2.sol
> +      revert ErrReachedDailyWithdrawalLimit();
```suggestion
    if (!(_receipt.info.erc == Token.Standard.ERC721 || !_reachedWithdrawalLimit(_tokenAddr, _quantity))) {
      revert ErrReachedDailyWithdrawalLimit();
    }
```

2023-06-12 07:33 UTC, nxqbao commented on contracts/ronin/staking/BaseStaking.sol
>    }
Please help me rename `notPoolAdmin` into `onlyNotPoolAdmin` for adapting code convention.

2023-06-12 07:33 UTC, nxqbao commented on contracts/ronin/staking/BaseStaking.sol
>    modifier poolIsActive(address _poolAddr) {
Please help me rename `poolIsActive` into `onlyActivePool` for adapting code convention.

2023-06-12 08:58 UTC, nxqbao approved these changes
Please update the table of changes in the PR.

2023-06-12 09:20 UTC, nxqbao approved these changes

2023-06-12 10:15 UTC, nxqbao commented on contracts/libraries/Token.sol
> +    if (!_success) revert ErrTokenCouldNotTransferFrom(_info, address(this), _to, _token);
Should declare a new error `ErrTokenCouldNotTransfer` to distinguish from `ErrTokenCouldNotTransferFrom`.

2023-06-15 04:56 UTC, merged